var regions = {
    "bandle-city": "Bandle City",
    "bilgewater": "Bilgewater",
    "demacia": "Demacia",
    "freljord": "Freljord",
    "ionia": "Ionia",
    "ixtal": "Ixtal",
    "mount-targon": "Mt. Targon",
    "noxus": "Noxus",
    "piltover": "Piltover",
    "runeterra": "Runeterra",
    "shadow-isles": "Shadow Isles",
    "shurima": "Shurima",
    "void": "Void",
    "zaun": "Zaun",
}

var champions = {
    "Aatrox": "runeterra",
    "Ahri": "ionia",
    "Akali": "ionia",
    "Alistar": "runeterra",
    "Amumu": "shurima",
    "Anivia": "freljord",
    "Annie": "runeterra",
    "Ashe": "freljord",
    "Aurelion Sol": "runeterra",
    "Azir": "shurima",
    "Bard": "runeterra",
    "Blitzcrank": "zaun",
    "Brand": "runeterra",
    "Braum": "freljord",
    "Caitlyn": "piltover",
    "Camille": "piltover",
    "Cassiopeia": "noxus",
    "Cho'Gath": "void",
    "Corki": "bandle-city",
    "Darius": "noxus",
    "Diana": "mount-targon",
    "Dr. Mundo": "zaun",
    "Draven": "noxus",
    "Ekko": "zaun",
    "Elise": "shadow-isles",
    "Evelynn": "runeterra",
    "Ezreal": "piltover",
    "Fiddlesticks": "runeterra",
    "Fiora": "demacia",
    "Fizz": "runeterra",
    "Galio": "demacia",
    "Gangplank": "bilgewater",
    "Garen": "demacia",
    "Gnar": "freljord",
    "Gragas": "freljord",
    "Graves": "bilgewater",
    "Hecarim": "shadow-isles",
    "Heimerdinger": "piltover",
    "Illaoi": "bilgewater",
    "Irelia": "ionia",
    "Ivern": "ionia",
    "Janna": "zaun",
    "Jarvan IV": "demacia",
    "Jax": "runeterra",
    "Jayce": "piltover",
    "Jhin": "ionia",
    "Jinx": "zaun",
    "Kai'Sa": "void",
    "Kalista": "shadow-isles",
    "Karma": "ionia",
    "Karthus": "shadow-isles",
    "Kassadin": "void",
    "Katarina": "noxus",
    "Kayle": "demacia",
    "Kayn": "ionia",
    "Kennen": "ionia",
    "Kha'Zix": "void",
    "Kindred": "runeterra",
    "Kled": "noxus",
    "Kog'Maw": "void",
    "LeBlanc": "noxus",
    "Lee Sin": "ionia",
    "Leona": "mount-targon",
    "Lissandra": "freljord",
    "Lucian": "demacia",
    "Lulu": "bandle-city",
    "Lux": "demacia",
    "Malphite": "ixtal",
    "Malzahar": "void",
    "Maokai": "shadow-isles",
    "Master Yi": "ionia",
    "Miss Fortune": "bilgewater",
    "Mordekaiser": "noxus",
    "Morgana": "demacia",
    "Nami": "runeterra",
    "Nasus": "shurima",
    "Nautilus": "bilgewater",
    "Neeko": "ixtal",
    "Nidalee": "ixtal",
    "Nocturne": "runeterra",
    "Nunu & Willump": "freljord",
    "Olaf": "freljord",
    "Orianna": "piltover",
    "Ornn": "freljord",
    "Pantheon": "mount-targon",
    "Poppy": "demacia",
    "Pyke": "bilgewater",
    "Qiyana": "ixtal",
    "Quinn": "demacia",
    "Rakan": "ionia",
    "Rammus": "shurima",
    "Rek'Sai": "void",
    "Renekton": "shurima",
    "Rengar": "ixtal",
    "Riven": "noxus",
    "Rumble": "bandle-city",
    "Ryze": "runeterra",
    "Sejuani": "freljord",
    "Shaco": "runeterra",
    "Shen": "ionia",
    "Shyvana": "demacia",
    "Singed": "zaun",
    "Sion": "noxus",
    "Sivir": "shurima",
    "Skarner": "shurima",
    "Sona": "demacia",
    "Soraka": "mount-targon",
    "Swain": "noxus",
    "Sylas": "demacia",
    "Syndra": "ionia",
    "Tahm Kench": "runeterra",
    "Taliyah": "shurima",
    "Talon": "noxus",
    "Taric": "mount-targon",
    "Teemo": "bandle-city",
    "Thresh": "shadow-isles",
    "Tristana": "bandle-city",
    "Trundle": "freljord",
    "Tryndamere": "freljord",
    "Twisted Fate": "bilgewater",
    "Twitch": "zaun",
    "Udyr": "freljord",
    "Urgot": "zaun",
    "Varus": "ionia",
    "Vayne": "demacia",
    "Veigar": "bandle-city",
    "Vel'Koz": "void",
    "Vi": "piltover",
    "Viktor": "zaun",
    "Vladimir": "noxus",
    "Volibear": "freljord",
    "Warwick": "zaun",
    "Wukong": "ionia",
    "Xayah": "ionia",
    "Xerath": "shurima",
    "Xin Zhao": "demacia",
    "Yasuo": "ionia",
    "Yorick": "shadow-isles",
    "Yuumi": "bandle-city",
    "Zac": "zaun",
    "Zed": "ionia",
    "Ziggs": "zaun",
    "Zilean": "runeterra",
    "Zoe": "mount-targon",
    "Zyra": "ixtal",
};

var override_tags = {
    "Burning Tides": {"champions": ["Twisted Fate", "Graves"],"regions": ["Bilgewater"], "authors": ["Scott Hawkes", "George Krstic", "Anthony Reynolds", "John O'Bryan"]},
    "Down Among The Dead Men": {"champions": ["Miss Fortune"], "regions": ["Bilgewater"], "authors": ["Graham McNeill"]},
    "Interview: Inside K/DA":  {"champions": ["Ahri", "Kai'Sa", "Akali", "Evelynn"], "regions": [], "authors": ["Indu Reddy", "Jared Rosen"]},
    "POP/STARS": {"champions": ["Ahri", "Kai'Sa", "Akali", "Evelynn"], "regions": [], "authors": ["Jared Rosen"]},
    "Trial of the Masks": {"champions": ["Sivir"], "regions": [], "authors": ["Jared Rosen"]},
    "The Lure": {"champions": ["Kayn", "Sona"], "regions": [], "authors": ["Dan Abnett"]},
    "The Man With the Grinning Shadow": {"champions": ["Lucian", "Thresh", "Alistar", "Urgot", "Karthus"], "regions": [], "authors": ["Jared Rosen"]}
};

var add_tags = {
    "Of Rats and Cats<br> and Neon Mice": ["Jhin", "Vi", "Vayne"],
    "The Slumber Party Summoning": ["Lux", "Ezreal", "Miss Fortune", "Soraka", "Poppy", "Lulu", "Janna", "Jinx"],
    "At The Edge Of The World": ["Zyra", "Noxus"],
    "The Mountain": ["Mt. Targon", "Leona", "Diana", "Zoe", "Pantheon", "Taric"],
    "Starfall": ["Lux", "Ezreal", "Miss Fortune", "Soraka", "Poppy", "Lulu", "Janna", "Jinx", "Ahri", "Syndra"],
    "The Legend of the Darkin": ["Kayn", "Aatrox", "Varus"],
    "Twilight of the Gods": ["Zoe", "Kayn", "Aatrox", "Varus"],
    "Bloodline": ["Sivir"],
    "The Whispering Doodad": ["Draven", "Noxus"],
    "What Once Sailed Free": ["Jarvan IV"],
    "Where Icathia Once Stood": ["Void", "Shurima"],
};

var authors = {
    "A Sword Without a Sheath": ["Robert Lo", "Joe Lansford"],
    "Greed and Tears": ["Anthony Reynolds"],
    "Twin Dawns": ["Matthew Dunn"],
    "Arisen": ["Anthony Reynolds"],
    "Ensemble": ["Rayla Heide"],
    "Tomb of the Troll Boy": ["Leslee Sullivant"],
    "The Thrill of the Chase": ["Graham McNeill"],
    "Tea with the Gray Lady": ["Ariel Lawrence"],
    "Canticle of the Winged Sisters": ["Graham McNeill"],
    "The Shedding of Skin": ["Rayla Heide"],
    "Night’s Work": ["Graham McNeill"],
    "Do No Harm": ["Anthony Burch"],
    "Lullaby": ["Matthew Dunn"],
    "Strand by Silken Strand": ["Graham McNeill"],
    "The Tallest Daisy": ["John O'Bryan"],
    "To Our End": ["Rayla Heide"],
    "A Matter of Honor": ["Graham McNeill"],
    "Blood in the Water": ["Anthony Reynolds"],
    "The Soldier and the Hag": ["Graham McNeill"],
    "One Last Shot": ["Anthony Reynolds"],
    "No One Lives": ["Graham McNeill"],
    "From the Journal of Professor Cecil B. Heimerdinger": ["Unknown Author"],
    "The Burden": ["Odin Shafer"],
    "Gift of Venom": ["Matthew Dunn"],
    "Deep Breath": ["Anthony Burch"],
    "None Shall Pass": ["Graham McNeill"],
    "A Quick Fix": ["Anthony Burch"],
    "The Wedding Crasher": ["Graham McNeill"],
    "Invocation": ["Graham McNeill"],
    "Burial At Sea": ["Graham McNeill"],
    "Forest for the Trees": ["Matthew Dunn"],
    "Where the Drakalops Roam": ["Odin Shafer"],
    "All That Glitters...": ["Graham McNeill"],
    "The Light Bringer": ["Graham McNeill"],
    "Last Light": ["Graham McNeill"],
    "Nightbloom": ["Rayla Heide"],
    "The Mountain": ["Graham McNeill"],
    "First Steps": ["Rayla Heide"],
    "Fieram": ["Rayla Heide"],
    "The Spear of Targon": ["Anthony Reynolds"],
    "The Slayer": ["John O'Bryan"],
    "Rules of Survival": ["Graham McNeill"],
    "Caravan North": ["Rayla Heide"],
    "Sai Kahleek": ["Odin Shafer"],
    "Darkness Renews": ["Graham McNeill"],
    "An Old Friend": ["John O'Bryan"],
    "The Princeling’s Lament": ["Graham McNeill"],
    "True Neutral": ["John O'Bryan"],
    "The Winged Beast": ["Rayla Heide"],
    "Engineering the Nightmare": ["Phillip Vargas"],
    "In the Mind of Madness": ["Randy Begel"],
    "Water": ["Odin Shafer"],
    "Dreamsong": ["Rayla Heide"],
    "Echoes in the Stone": ["Ariel Lawrence"],
    "The Uninvited Guest": ["George Krstic"],
    "The Legend of the Darkin": ["Graham McNeill"],
    "The Road to Ruin": ["Robert Lo", "Joe Lansford"],
    "The Collection": ["Rayla Heide"],
    "A Quiet Night": ["Graham McNeill"],
    "Double Down": ["Graham McNeill"],
    "Do Not Engage": ["Iain Hendry"],
    "Eduard Santangelo's Vastaya Field Journal": ["Anthony Burch"],
    "Monsters": ["Graham McNeill"],
    "Interrogation 101": ["Graham McNeill"],
    "House on Emberflit Alley": ["Rayla Heide"],
    "If They Run": ["David Slagle"],
    "Unbound": ["Anthony Reynolds"],
    "Last Rites": ["John O'Bryan"],
    "Protection": ["Graham McNeill"],
    "Meet Zoe":    ["Odin Shafer"],
}
