const champions_base = {
    "aatrox": "runeterra",
    "ahri": "ionia",
    "akali": "ionia",
    "alistar": "runeterra",
    "amumu": "shurima",
    "anivia": "freljord",
    "annie": "runeterra",
    "ashe": "freljord",
    "aurelionsol": "runeterra",
    "azir": "shurima",
    "bard": "runeterra",
    "blitzcrank": "zaun",
    "brand": "runeterra",
    "braum": "freljord",
    "caitlyn": "piltover",
    "camille": "piltover",
    "cassiopeia": "noxus",
    "chogath": "void",
    "corki": "bandle_city",
    "darius": "noxus",
    "diana": "mount_targon",
    "draven": "noxus",
    "drmundo": "zaun",
    "ekko": "zaun",
    "elise": "shadow_isles",
    "evelynn": "runeterra",
    "ezreal": "piltover",
    "fiddlesticks": "runeterra",
    "fiora": "demacia",
    "fizz": "runeterra",
    "galio": "demacia",
    "gangplank": "bilgewater",
    "garen": "demacia",
    "gnar": "freljord",
    "gragas": "freljord",
    "graves": "bilgewater",
    "hecarim": "shadow_isles",
    "heimerdinger": "piltover",
    "illaoi": "bilgewater",
    "irelia": "ionia",
    "ivern": "ionia",
    "janna": "zaun",
    "jarvaniv": "demacia",
    "jax": "runeterra",
    "jayce": "piltover",
    "jhin": "ionia",
    "jinx": "zaun",
    "kaisa": "void",
    "kalista": "shadow_isles",
    "karma": "ionia",
    "karthus": "shadow_isles",
    "kassadin": "void",
    "katarina": "noxus",
    "kayle": "demacia",
    "kayn": "ionia",
    "kennen": "ionia",
    "khazix": "void",
    "kindred": "runeterra",
    "kled": "noxus",
    "kogmaw": "void",
    "leblanc": "noxus",
    "leesin": "ionia",
    "leona": "mount_targon",
    "lissandra": "freljord",
    "lucian": "demacia",
    "lulu": "bandle_city",
    "lux": "demacia",
    "malphite": "ixtal",
    "malzahar": "void",
    "maokai": "shadow_isles",
    "masteryi": "ionia",
    "missfortune": "bilgewater",
    "monkeyking": "ionia",
    "mordekaiser": "noxus",
    "morgana": "demacia",
    "nami": "runeterra",
    "nasus": "shurima",
    "nautilus": "bilgewater",
    "neeko": "ixtal",
    "nidalee": "ixtal",
    "nocturne": "runeterra",
    "nunu": "freljord",
    "olaf": "freljord",
    "orianna": "piltover",
    "ornn": "freljord",
    "pantheon": "mount_targon",
    "poppy": "demacia",
    "pyke": "bilgewater",
    "qiyana": "ixtal",
    "quinn": "demacia",
    "rakan": "ionia",
    "rammus": "shurima",
    "reksai": "void",
    "renekton": "shurima",
    "rengar": "ixtal",
    "riven": "noxus",
    "rumble": "bandle_city",
    "ryze": "runeterra",
    "sejuani": "freljord",
    "shaco": "runeterra",
    "shen": "ionia",
    "shyvana": "demacia",
    "singed": "zaun",
    "sion": "noxus",
    "sivir": "shurima",
    "skarner": "shurima",
    "sona": "demacia",
    "soraka": "mount_targon",
    "swain": "noxus",
    "sylas": "demacia",
    "syndra": "ionia",
    "tahmkench": "runeterra",
    "taliyah": "shurima",
    "talon": "noxus",
    "taric": "mount_targon",
    "teemo": "bandle_city",
    "thresh": "shadow_isles",
    "tristana": "bandle_city",
    "trundle": "freljord",
    "tryndamere": "freljord",
    "twistedfate": "bilgewater",
    "twitch": "zaun",
    "udyr": "freljord",
    "urgot": "zaun",
    "varus": "ionia",
    "vayne": "demacia",
    "veigar": "bandle_city",
    "velkoz": "void",
    "vi": "piltover",
    "viktor": "zaun",
    "vladimir": "noxus",
    "volibear": "freljord",
    "warwick": "zaun",
    "xayah": "ionia",
    "xerath": "shurima",
    "xinzhao": "demacia",
    "yasuo": "ionia",
    "yorick": "shadow_isles",
    "yuumi": "bandle_city",
    "zac": "zaun",
    "zed": "ionia",
    "ziggs": "zaun",
    "zilean": "runeterra",
    "zoe": "mount_targon",
    "zyra": "ixtal"
};

const override_tags = {
    "bilgewater-story": {"champions": ["twistedfate", "graves"],"regions": ["bilgewater"], "authors": ["Scott Hawkes", "George Krstic", "Anthony Reynolds", "John O'Bryan"]},
    "popstar-interview":  {"champions": ["ahri", "kaisa", "akali", "evelynn"], "regions": [], "authors": ["Indu Reddy", "Jared Rosen"]},
    "popstars-lyrics": {"champions": ["ahri", "kaisa", "akali", "evelynn"], "regions": [], "authors": ["Jared Rosen"]},
    "trial-of-the-masks": {"champions": ["sivir"], "regions": [], "authors": ["Jared Rosen"]},
    "the-lure": {"champions": ["kayn", "sona"], "regions": [], "authors": ["Dan Abnett"]},
    "the-man-with-the-grinning-shadow": {"champions": ["lucian", "thresh", "alistar", "urgot", "karthus"], "regions": [], "authors": ["Jared Rosen"]}
};

const add_tags = {
    "project-of-rats-and-cats-and-neon-mice": {"champions": ["jhin", "vi", "vayne"]},
    "pajama-party": {"champions": ["lux", "ezreal", "missfortune", "soraka", "poppy", "lulu", "janna", "jinx"]},
    "at-the-edge-of-the-world": {"champions": ["zyra"], "regions":  ["noxus"]},
    "mount-targon-story": {"regions": ["mount_targon"], "champions": ["leona", "diana", "zoe", "pantheon", "taric"], "authors": ["Graham McNeill"]},
    "star-guardian-starfall": {"champions": ["lux", "ezreal", "missfortune", "soraka", "poppy", "lulu", "janna", "jinx", "ahri", "syndra"]},
    "the-legend-of-the-darkin": {"champions": ["kayn", "aatrox", "varus"], "authors": ["Graham McNeill"]},
    "twilight-of-the-gods": {"champions": ["zoe", "kayn", "aatrox", "varus"]},
    "rg-shurima-story": {"champions": ["sivir"]},
    "the-whispering-doodad": {"champions": ["draven"], "regions": ["noxus"]},
    "whatoncesailedfree": {"champions": ["jarvaniv"]},
    "where-icathia-once-stood": {"regions": ["void", "shurima"]},
};

const authors_fallback = {
    "a-sword-without-a-sheath-story": ["Robert Lo", "Joe Lansford"],
    "amumu-color-story": ["Anthony Reynolds"],
    "aurelionsol-color-story": ["Matthew Dunn"],
    "azir-color-story": ["Anthony Reynolds"],
    "blitzcrank-color-story": ["Rayla Heide"],
    "braum-color-story": ["Leslee Sullivant"],
    "caitlyn-color-story": ["Graham McNeill"],
    "camille-color-story": ["Ariel Lawrence"],
    "canticleofthewingedsisters": ["Graham McNeill"],
    "cassiopeia-color-story": ["Rayla Heide"],
    "diana-color-story": ["Graham McNeill"],
    "drmundo-color-story": ["Anthony Burch"],
    "ekko-color-story": ["Matthew Dunn"],
    "elise-color-story": ["Graham McNeill"],
    "evelynn-color-story": ["John O'Bryan"],
    "fiddlesticks-color-story": ["Rayla Heide"],
    "fiora-color-story": ["Graham McNeill"],
    "gangplank-color-story": ["Anthony Reynolds"],
    "garen-color-story": ["Graham McNeill"],
    "graves-color-story": ["Anthony Reynolds"],
    "hecarim-color-story": ["Graham McNeill"],
    "illaoi-color-story": ["Odin Austin Shafer"],
    "ivern-color-story": ["Matthew Dunn"],
    "janna-color-story": ["Anthony Burch"],
    "jax-color-story": ["Graham McNeill"],
    "jayce-color-story": ["Anthony Burch"],
    "jinx-color-story": ["Graham McNeill"],
    "kalista-color-story": ["Graham McNeill"],
    "karthus-color-story": ["Graham McNeill"],
    "kindred-color-story": ["Matthew Dunn"],
    "kled-color-story": ["Odin Austin Shafer"],
    "leesin-color-story": ["Graham McNeill"],
    "leona-color-story": ["Graham McNeill"],
    "lux-color-story": ["Graham McNeill"],
    "maokai-color-story": ["Rayla Heide"],
    "missfortune-color-story": ["Graham McNeill"],
    "nami-first-steps": ["Rayla Heide"],
    "orianna-color-story": ["Rayla Heide"],
    "pantheon-fallen-story": ["David Slagle"],
    "poppy-color-story": ["John O'Bryan"],
    "quinn-color-story": ["Graham McNeill"],
    "rammus-color-story": ["Rayla Heide"],
    "reksai-color-story": ["Odin Austin Shafer"],
    "renekton-color-story": ["Graham McNeill"],
    "ryze-color-story": ["John O'Bryan"],
    "shadow-isles-story": ["Graham McNeill"],
    "shen-color-story": ["John O'Bryan"],
    "shyvana-color-story": ["Rayla Heide"],
    "singed-thenightmare-story": ["Phillip Vargas"],
    "sion-color-story": ["Randy Begel"],
    "sivir-color-story": ["Odin Austin Shafer"],
    "skarner-color-story": ["Rayla Heide"],
    "taliyah-color-story": ["Ariel Lawrence"],
    "taric-color-story": ["George Krstic"],
    "the-road-to-ruin-story": ["Robert Lo", "Joe Lansford"],
    "thresh-color-story": ["Rayla Heide"],
    "tristana-color-story": ["Graham McNeill"],
    "twistedfate-color-story": ["Graham McNeill"],
    "twitch-color-story": ["Iain Hendry"],
    "vastaya-field-journal": ["Anthony Burch"],
    "vayne-color-story": ["Graham McNeill"],
    "vi-color-story": ["Graham McNeill"],
    "viktor-color-story": ["Rayla Heide"],
    "warwick-color-story": ["David Slagle"],
    "xerath-color-story": ["Anthony Reynolds"],
    "yorick-color-story": ["John O'Bryan"],
    "zac-color-story": ["Graham McNeill"],
    "zoe-color-story":    ["Odin Austin Shafer"],
}
