const regions = {
    "bandle-city": "Bandle City",
    "bilgewater": "Bilgewater",
    "demacia": "Demacia",
    "freljord": "Freljord",
    "ionia": "Ionia",
    "ixtal": "Ixtal",
    "mount-targon": "Mt. Targon",
    "noxus": "Noxus",
    "piltover": "Piltover",
    "runeterra": "Runeterra",
    "shadow-isles": "Shadow Isles",
    "shurima": "Shurima",
    "void": "Void",
    "zaun": "Zaun",
}

const champions = {
    "Aatrox": "Runeterra",
    "Ahri": "Ionia",
    "Akali": "Ionia",
    "Alistar": "Runeterra",
    "Amumu": "Shurima",
    "Anivia": "Freljord",
    "Annie": "Runeterra",
    "Ashe": "Freljord",
    "Aurelion Sol": "Runeterra",
    "Azir": "Shurima",
    "Bard": "Runeterra",
    "Blitzcrank": "Zaun",
    "Brand": "Runeterra",
    "Braum": "Freljord",
    "Caitlyn": "Piltover",
    "Camille": "Piltover",
    "Cassiopeia": "Noxus",
    "Cho'Gath": "Void",
    "Corki": "Bandle City",
    "Darius": "Noxus",
    "Diana": "Mt. Targon",
    "Dr. Mundo": "Zaun",
    "Draven": "Noxus",
    "Ekko": "Zaun",
    "Elise": "Shadow Isles",
    "Evelynn": "Runeterra",
    "Ezreal": "Piltover",
    "Fiddlesticks": "Runeterra",
    "Fiora": "Demacia",
    "Fizz": "Runeterra",
    "Galio": "Demacia",
    "Gangplank": "Bilgewater",
    "Garen": "Demacia",
    "Gnar": "Freljord",
    "Gragas": "Freljord",
    "Graves": "Bilgewater",
    "Hecarim": "Shadow Isles",
    "Heimerdinger": "Piltover",
    "Illaoi": "Bilgewater",
    "Irelia": "Ionia",
    "Ivern": "Ionia",
    "Janna": "Zaun",
    "Jarvan IV": "Demacia",
    "Jax": "Runeterra",
    "Jayce": "Piltover",
    "Jhin": "Ionia",
    "Jinx": "Zaun",
    "Kai'Sa": "Void",
    "Kalista": "Shadow Isles",
    "Karma": "Ionia",
    "Karthus": "Shadow Isles",
    "Kassadin": "Void",
    "Katarina": "Noxus",
    "Kayle": "Demacia",
    "Kayn": "Ionia",
    "Kennen": "Ionia",
    "Kha'Zix": "Void",
    "Kindred": "Runeterra",
    "Kled": "Noxus",
    "Kog'Maw": "Void",
    "LeBlanc": "Noxus",
    "Lee Sin": "Ionia",
    "Leona": "Mt. Targon",
    "Lissandra": "Freljord",
    "Lucian": "Demacia",
    "Lulu": "Bandle City",
    "Lux": "Demacia",
    "Malphite": "Ixtal",
    "Malzahar": "Void",
    "Maokai": "Shadow Isles",
    "Master Yi": "Ionia",
    "Miss Fortune": "Bilgewater",
    "Mordekaiser": "Noxus",
    "Morgana": "Demacia",
    "Nami": "Runeterra",
    "Nasus": "Shurima",
    "Nautilus": "Bilgewater",
    "Neeko": "Ixtal",
    "Nidalee": "Ixtal",
    "Nocturne": "Runeterra",
    "Nunu & Willump": "Freljord",
    "Olaf": "Freljord",
    "Orianna": "Piltover",
    "Ornn": "Freljord",
    "Pantheon": "Mt. Targon",
    "Poppy": "Demacia",
    "Pyke": "Bilgewater",
    "Qiyana": "Ixtal",
    "Quinn": "Demacia",
    "Rakan": "Ionia",
    "Rammus": "Shurima",
    "Rek'Sai": "Void",
    "Renekton": "Shurima",
    "Rengar": "Ixtal",
    "Riven": "Noxus",
    "Rumble": "Bandle City",
    "Ryze": "Runeterra",
    "Sejuani": "Freljord",
    "Shaco": "Runeterra",
    "Shen": "Ionia",
    "Shyvana": "Demacia",
    "Singed": "Zaun",
    "Sion": "Noxus",
    "Sivir": "Shurima",
    "Skarner": "Shurima",
    "Sona": "Demacia",
    "Soraka": "Mt. Targon",
    "Swain": "Noxus",
    "Sylas": "Demacia",
    "Syndra": "Ionia",
    "Tahm Kench": "Runeterra",
    "Taliyah": "Shurima",
    "Talon": "Noxus",
    "Taric": "Mt. Targon",
    "Teemo": "Bandle City",
    "Thresh": "Shadow Isles",
    "Tristana": "Bandle City",
    "Trundle": "Freljord",
    "Tryndamere": "Freljord",
    "Twisted Fate": "Bilgewater",
    "Twitch": "Zaun",
    "Udyr": "Freljord",
    "Urgot": "Zaun",
    "Varus": "Ionia",
    "Vayne": "Demacia",
    "Veigar": "Bandle City",
    "Vel'Koz": "Void",
    "Vi": "Piltover",
    "Viktor": "Zaun",
    "Vladimir": "Noxus",
    "Volibear": "Freljord",
    "Warwick": "Zaun",
    "Wukong": "Ionia",
    "Xayah": "Ionia",
    "Xerath": "Shurima",
    "Xin Zhao": "Demacia",
    "Yasuo": "Ionia",
    "Yorick": "Shadow Isles",
    "Yuumi": "Bandle City",
    "Zac": "Zaun",
    "Zed": "Ionia",
    "Ziggs": "Zaun",
    "Zilean": "Runeterra",
    "Zoe": "Mt. Targon",
    "Zyra": "Ixtal",
};

const override_tags = {
    "Burning Tides": {"champions": ["Twisted Fate", "Graves"],"regions": ["Bilgewater"], "authors": ["Scott Hawkes", "George Krstic", "Anthony Reynolds", "John O'Bryan"]},
    "Down Among The Dead Men": {"champions": ["Miss Fortune"], "regions": ["Bilgewater"], "authors": ["Graham McNeill"]},
    "Interview: Inside K/DA":  {"champions": ["Ahri", "Kai'Sa", "Akali", "Evelynn"], "regions": [], "authors": ["Indu Reddy", "Jared Rosen"]},
    "POP/STARS": {"champions": ["Ahri", "Kai'Sa", "Akali", "Evelynn"], "regions": [], "authors": ["Jared Rosen"]},
    "Trial of the Masks": {"champions": ["Sivir"], "regions": [], "authors": ["Jared Rosen"]},
    "The Lure": {"champions": ["Kayn", "Sona"], "regions": [], "authors": ["Dan Abnett"]},
    "The Man With the Grinning Shadow": {"champions": ["Lucian", "Thresh", "Alistar", "Urgot", "Karthus"], "regions": [], "authors": ["Jared Rosen"]}
};

const add_tags = {
    "Of Rats and Cats<br> and Neon Mice": {"champions": ["Jhin", "Vi", "Vayne"]},
    "The Slumber Party Summoning": {"champions": ["Lux", "Ezreal", "Miss Fortune", "Soraka", "Poppy", "Lulu", "Janna", "Jinx"]},
    "At The Edge Of The World": {"champions": ["Zyra"], "regions":  ["Noxus"]},
    "The Mountain": {"regions": ["Mt. Targon"], "champions": ["Leona", "Diana", "Zoe", "Pantheon", "Taric"]},
    "Starfall": {"champions": ["Lux", "Ezreal", "Miss Fortune", "Soraka", "Poppy", "Lulu", "Janna", "Jinx", "Ahri", "Syndra"]},
    "The Legend of the Darkin": {"champions": ["Kayn", "Aatrox", "Varus"]},
    "Twilight of the Gods": {"champions": ["Zoe", "Kayn", "Aatrox", "Varus"]},
    "Bloodline": {"champions": ["Sivir"]},
    "The Whispering Doodad": {"champions": ["Draven"], "regions": ["Noxus"]},
    "What Once Sailed Free": {"champions": ["Jarvan IV"]},
    "Where Icathia Once Stood": {"regions": ["Void", "Shurima"]},
};

const authors_fallback = {
    "A Sword Without a Sheath": ["Robert Lo", "Joe Lansford"],
    "Greed and Tears": ["Anthony Reynolds"],
    "Twin Dawns": ["Matthew Dunn"],
    "Arisen": ["Anthony Reynolds"],
    "Ensemble": ["Rayla Heide"],
    "Tomb of the Troll Boy": ["Leslee Sullivant"],
    "The Thrill of the Chase": ["Graham McNeill"],
    "Tea with the Gray Lady": ["Ariel Lawrence"],
    "Canticle of the Winged Sisters": ["Graham McNeill"],
    "The Shedding of Skin": ["Rayla Heide"],
    "Night’s Work": ["Graham McNeill"],
    "Do No Harm": ["Anthony Burch"],
    "Lullaby": ["Matthew Dunn"],
    "Strand by Silken Strand": ["Graham McNeill"],
    "The Tallest Daisy": ["John O'Bryan"],
    "To Our End": ["Rayla Heide"],
    "A Matter of Honor": ["Graham McNeill"],
    "Blood in the Water": ["Anthony Reynolds"],
    "The Soldier and the Hag": ["Graham McNeill"],
    "One Last Shot": ["Anthony Reynolds"],
    "No One Lives": ["Graham McNeill"],
    "From the Journal of Professor Cecil B. Heimerdinger": ["Unknown Author"],
    "The Burden": ["Odin Shafer"],
    "Gift of Venom": ["Matthew Dunn"],
    "Deep Breath": ["Anthony Burch"],
    "None Shall Pass": ["Graham McNeill"],
    "A Quick Fix": ["Anthony Burch"],
    "The Wedding Crasher": ["Graham McNeill"],
    "Invocation": ["Graham McNeill"],
    "Burial At Sea": ["Graham McNeill"],
    "Forest for the Trees": ["Matthew Dunn"],
    "Where the Drakalops Roam": ["Odin Shafer"],
    "All That Glitters...": ["Graham McNeill"],
    "The Light Bringer": ["Graham McNeill"],
    "Last Light": ["Graham McNeill"],
    "Nightbloom": ["Rayla Heide"],
    "The Mountain": ["Graham McNeill"],
    "First Steps": ["Rayla Heide"],
    "Fieram": ["Rayla Heide"],
    "The Spear of Targon": ["Anthony Reynolds"],
    "The Slayer": ["John O'Bryan"],
    "Rules of Survival": ["Graham McNeill"],
    "Caravan North": ["Rayla Heide"],
    "Sai Kahleek": ["Odin Shafer"],
    "Darkness Renews": ["Graham McNeill"],
    "An Old Friend": ["John O'Bryan"],
    "The Princeling’s Lament": ["Graham McNeill"],
    "True Neutral": ["John O'Bryan"],
    "The Winged Beast": ["Rayla Heide"],
    "Engineering the Nightmare": ["Phillip Vargas"],
    "In the Mind of Madness": ["Randy Begel"],
    "Water": ["Odin Shafer"],
    "Dreamsong": ["Rayla Heide"],
    "Echoes in the Stone": ["Ariel Lawrence"],
    "The Uninvited Guest": ["George Krstic"],
    "The Legend of the Darkin": ["Graham McNeill"],
    "The Road to Ruin": ["Robert Lo", "Joe Lansford"],
    "The Collection": ["Rayla Heide"],
    "A Quiet Night": ["Graham McNeill"],
    "Double Down": ["Graham McNeill"],
    "Do Not Engage": ["Iain Hendry"],
    "Eduard Santangelo's Vastaya Field Journal": ["Anthony Burch"],
    "Monsters": ["Graham McNeill"],
    "Interrogation 101": ["Graham McNeill"],
    "House on Emberflit Alley": ["Rayla Heide"],
    "If They Run": ["David Slagle"],
    "Unbound": ["Anthony Reynolds"],
    "Last Rites": ["John O'Bryan"],
    "Protection": ["Graham McNeill"],
    "Meet Zoe":    ["Odin Shafer"],
    "For Those Who Have Fallen": ["David Slagle"],
}
